#include <ctype.h>
#include <string.h>
#include "lexer.h"
static Token make_token(TokenType type,const char *text,int line,int column){Token t={0};t.type=type;strncpy(t.lexeme,text,MAX_LEXEME-1);t.line=line;t.column=column;return t;}
const char *token_type_name(TokenType t){switch(t){case TOK_EOF:return "EOF";case TOK_CREAR:return "CREAR";case TOK_COMO:return "COMO";case TOK_ENTERO:return "ENTERO";case TOK_DECIMAL:return "DECIMAL";case TOK_TEXTO:return "TEXTO";case TOK_BOOLEANO:return "BOOLEANO";case TOK_CARACTER:return "CARACTER";case TOK_VERDADERO:return "VERDADERO";case TOK_FALSO:return "FALSO";case TOK_IDENTIFICADOR:return "IDENTIFICADOR";case TOK_NUM_ENTERO:return "NUM_ENTERO";case TOK_NUM_DECIMAL:return "NUM_DECIMAL";case TOK_TEXTO_LITERAL:return "TEXTO_LITERAL";case TOK_CARACTER_LITERAL:return "CARACTER_LITERAL";case TOK_IGUAL:return "IGUAL";case TOK_PUNTO_COMA:return "PUNTO_COMA";default:return "ERROR";}}
static void adv(Lexer*l){if(l->source[l->pos]=='\n'){l->line++;l->column=1;}else l->column++;l->pos++;}
void lexer_init(Lexer*l,const char*s){l->source=s;l->pos=0;l->line=1;l->column=1;}
Token lexer_next(Lexer*l){while(isspace((unsigned char)l->source[l->pos]))adv(l);int line=l->line,col=l->column;char c=l->source[l->pos];if(!c)return make_token(TOK_EOF,"EOF",line,col);
if(isalpha((unsigned char)c)||c=='_'){char b[MAX_LEXEME];int n=0;while(isalnum((unsigned char)l->source[l->pos])||l->source[l->pos]=='_'){if(n<MAX_LEXEME-1)b[n++]=l->source[l->pos];adv(l);}b[n]=0;
if(!strcmp(b,"crear"))return make_token(TOK_CREAR,b,line,col);if(!strcmp(b,"como"))return make_token(TOK_COMO,b,line,col);if(!strcmp(b,"entero"))return make_token(TOK_ENTERO,b,line,col);if(!strcmp(b,"decimal"))return make_token(TOK_DECIMAL,b,line,col);if(!strcmp(b,"texto"))return make_token(TOK_TEXTO,b,line,col);if(!strcmp(b,"booleano"))return make_token(TOK_BOOLEANO,b,line,col);if(!strcmp(b,"caracter"))return make_token(TOK_CARACTER,b,line,col);if(!strcmp(b,"verdadero"))return make_token(TOK_VERDADERO,b,line,col);if(!strcmp(b,"falso"))return make_token(TOK_FALSO,b,line,col);return make_token(TOK_IDENTIFICADOR,b,line,col);}
if(isdigit((unsigned char)c)){char b[MAX_LEXEME];int n=0,d=0;while(isdigit((unsigned char)l->source[l->pos])||l->source[l->pos]=='.'){if(l->source[l->pos]=='.'){if(d)break;d=1;}if(n<MAX_LEXEME-1)b[n++]=l->source[l->pos];adv(l);}b[n]=0;return make_token(d?TOK_NUM_DECIMAL:TOK_NUM_ENTERO,b,line,col);}
if(c=='"'){char b[MAX_LEXEME];int n=0;adv(l);while(l->source[l->pos]&&l->source[l->pos]!='"'&&l->source[l->pos]!='\n'){if(n<MAX_LEXEME-1)b[n++]=l->source[l->pos];adv(l);}if(l->source[l->pos]!='"')return make_token(TOK_ERROR,"Cadena sin cerrar",line,col);adv(l);b[n]=0;return make_token(TOK_TEXTO_LITERAL,b,line,col);}
if(c=='\''){char b[2];adv(l);if(!l->source[l->pos]||l->source[l->pos]=='\n'||l->source[l->pos]=='\'')return make_token(TOK_ERROR,"Caracter invalido",line,col);b[0]=l->source[l->pos];b[1]=0;adv(l);if(l->source[l->pos]!='\'')return make_token(TOK_ERROR,"Caracter debe tener un simbolo",line,col);adv(l);return make_token(TOK_CARACTER_LITERAL,b,line,col);}
if(c=='='){adv(l);return make_token(TOK_IGUAL,"=",line,col);}if(c==';'){adv(l);return make_token(TOK_PUNTO_COMA,";",line,col);}char b[2]={c,0};adv(l);return make_token(TOK_ERROR,b,line,col);}
