#include <stdio.h>
#include <string.h>
#include "parser.h"
static void adv(Parser*p){p->current=lexer_next(&p->lexer);}static void err(Parser*p,const char*m){fprintf(stderr,"[SINTACTICO] Linea %d, columna %d: %s (token '%s')\n",p->current.line,p->current.column,m,p->current.lexeme);p->errors++;}static int expect(Parser*p,TokenType t,const char*m){if(p->current.type!=t){err(p,m);return 0;}adv(p);return 1;}
static const char*typename(TokenType t){switch(t){case TOK_ENTERO:return "entero";case TOK_DECIMAL:return "decimal";case TOK_TEXTO:return "texto";case TOK_BOOLEANO:return "booleano";case TOK_CARACTER:return "caracter";default:return NULL;}}
static int isvalue(TokenType t){return t==TOK_NUM_ENTERO||t==TOK_NUM_DECIMAL||t==TOK_TEXTO_LITERAL||t==TOK_CARACTER_LITERAL||t==TOK_VERDADERO||t==TOK_FALSO;}
static ASTNode*decl(Parser*p){expect(p,TOK_CREAR,"Se esperaba 'crear'");if(p->current.type!=TOK_IDENTIFICADOR){err(p,"Se esperaba nombre de variable");return NULL;}char n[128];strcpy(n,p->current.lexeme);adv(p);if(!expect(p,TOK_COMO,"Se esperaba 'como'"))return NULL;const char*t=typename(p->current.type);if(!t){err(p,"Tipo de dato invalido");return NULL;}char ty[128];strcpy(ty,t);adv(p);char v[128]="";if(p->current.type==TOK_IGUAL){adv(p);if(!isvalue(p->current.type)){err(p,"Se esperaba un valor");return NULL;}strcpy(v,p->current.lexeme);adv(p);}if(!expect(p,TOK_PUNTO_COMA,"Se esperaba ';'"))return NULL;return ast_create(AST_DECLARACION,n,ty,v);}
static ASTNode*assign(Parser*p){char n[128];strcpy(n,p->current.lexeme);adv(p);if(!expect(p,TOK_IGUAL,"Se esperaba '='"))return NULL;if(!isvalue(p->current.type)){err(p,"Se esperaba un valor valido");return NULL;}char v[128];strcpy(v,p->current.lexeme);adv(p);if(!expect(p,TOK_PUNTO_COMA,"Se esperaba ';'"))return NULL;return ast_create(AST_ASIGNACION,n,"",v);}
void parser_init(Parser*p,const char*s){lexer_init(&p->lexer,s);p->errors=0;p->current=lexer_next(&p->lexer);}ASTNode*parser_parse(Parser*p){ASTNode*r=NULL;while(p->current.type!=TOK_EOF){if(p->current.type==TOK_ERROR){err(p,"Token no reconocido");adv(p);continue;}ASTNode*n=NULL;if(p->current.type==TOK_CREAR)n=decl(p);else if(p->current.type==TOK_IDENTIFICADOR)n=assign(p);else{err(p,"Se esperaba declaracion o asignacion");adv(p);}if(n)ast_append(&r,n);}return r;}int parser_error_count(const Parser*p){return p->errors;}
